apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: p1
  spec:
    containers:
      - name: web
        image: registry.redhat.io/rhel8/nginx-116
    imagePullSecrets:
      - name: 13124705-ocpRhRegUser-pull-secret